(define (merge a b)
(cond ((null? a) b) ((null? b) a)
((< (car b) (car a)) (cons (car b) (merge a (cdr b))))
(else (cons (car a) (merge (cdr a) b)))))
(define (split l)
(let loop ((slow l) (fast l) (acc '()))
(if (or (null? fast) (null? (cdr fast))) (values (reverse acc) slow)
(loop (cdr slow) (cddr fast) (cons (car slow) acc)))))
(define (msort l)
(if (or (null? l) (null? (cdr l))) l
(call-with-values (lambda () (split l))
(lambda (a b) (merge (msort a) (msort b))))))
(define (build i acc) (if (= i 0) acc (build (- i 1) (cons (modulo (* i 7919) 2000) acc))))
(car (msort (build 1000 '())))
