// SPDX-License-Identifier: MIT

package scheme

import (
	"fmt"
	"runtime"
	"sort"
	"strings"
)

// Generating LLVM IR.
//
// The compiler in lower.go turns a Scheme form into bytecode for this process
// to run; this turns it into LLVM IR for a program that runs on its own.  They
// are two back ends over one front end: both read the same forms and both call
// the same primitives, so a program compiled to a native executable and the
// same program interpreted here agree about what it means.
//
// The shape of the generated program is a **hybrid**, which is the decision
// this file is built around:
//
//   - a **pure function** — one whose body only computes from its parameters and
//     constants, with no side effects and no call out of that set — is compiled
//     to native LLVM: real registers, real branches, a real call.  `(define
//     (add a b) (+ a b))` becomes four instructions, and the integers in it are
//     machine words rather than heap objects.
//   - **anything else** — a macro, a closure over mutable state, a call to a
//     builtin, a continuation — becomes a call into the runtime library, which
//     is the interpreter: the same evaluator this process runs, compiled into a
//     Go archive and linked in.
//
// The second half is what keeps the language whole.  A compiler that refused
// what it could not translate would be a compiler for a subset; one that hands
// the hard form to the runtime keeps `call/cc`, `dynamic-wind`, macros and every
// library working, and gets the native speed where a program spends its time.

// IRProgram is a generated program: the LLVM IR, and what was learned while
// generating it.
type IRProgram struct {
	// IR is the module, as LLVM assembly.
	IR string
	// Native is how many procedures were compiled to native code, and Runtime
	// how many were handed to the runtime library.  A caller reports the split,
	// because "why is this program not fast" is usually answered by it.
	Native  int
	Runtime int
}

// CompileToIR reads a script and generates a native program for it.
//
// The script is read here rather than by the runtime, so that a syntax error is
// reported by the compiler with the compiler's message and no tool is invoked.
func CompileToIR(source, name string) (*IRProgram, error) {
	r := NewStringReader(source)
	if name != "" {
		r.Source = name
	}
	forms, err := r.ReadAll()
	if err != nil {
		return nil, err
	}
	g := &irGen{module: newIRModule()}
	if err := g.program(forms); err != nil {
		return nil, err
	}
	return &IRProgram{IR: g.module.String(), Native: g.native, Runtime: g.runtime}, nil
}

// irGen holds the state of one generation.
type irGen struct {
	module  *irModule
	native  int
	runtime int
}

// ---------------------------------------------------------------------------
// The module builder
// ---------------------------------------------------------------------------

// irModule builds one LLVM module.  It is a string builder with the bookkeeping
// a module needs: the declarations already emitted, the string constants, and a
// counter for the registers and labels that have to be unique within a function.
type irModule struct {
	declsBuf  strings.Builder
	body      strings.Builder
	decls     map[string]bool
	strings   map[string]string // a string constant, and the global holding it
	nextReg   int
	nextLabel int
}

func newIRModule() *irModule {
	return &irModule{decls: map[string]bool{}, strings: map[string]string{}}
}

// reg returns a fresh SSA register name.
func (m *irModule) reg() string {
	m.nextReg++
	return fmt.Sprintf("%%t%d", m.nextReg)
}

// freshLabel returns a fresh basic-block label.
func (m *irModule) freshLabel(prefix string) string {
	m.nextLabel++
	return fmt.Sprintf("%s%d", prefix, m.nextLabel)
}

// declare records an external function the module calls, once.  Emitting the
// same declare twice is an LLVM error, and a program that calls display in two
// places is the normal case.
func (m *irModule) declare(sig string) {
	if m.decls[sig] {
		return
	}
	m.decls[sig] = true
	fmt.Fprintf(&m.declsBuf, "declare %s\n", sig)
}

// String returns the module as LLVM assembly.
func (m *irModule) String() string {
	var out strings.Builder
	out.WriteString("; Generated by goscheme compile.\n")
	out.WriteString("; Every call to a runtime function below is a call into the\n")
	out.WriteString("; interpreter, which is linked into the program.\n")
	fmt.Fprintf(&out, "target triple = %q\n\n", irTargetTriple())
	for _, sig := range m.sortedDecls() {
		fmt.Fprintf(&out, "declare %s\n", sig)
	}
	out.WriteString("\n")
	out.WriteString(m.body.String())
	return out.String()
}

func (m *irModule) sortedDecls() []string {
	out := make([]string, 0, len(m.decls))
	for d := range m.decls {
		out = append(out, d)
	}
	sort.Strings(out)
	return out
}

// irTargetTriple is the triple of the machine being compiled for.  The compiler
// runs where the program will run, so it is the host's; cross-compilation would
// read it from a flag.
func irTargetTriple() string {
	arch := "x86_64"
	switch runtime.GOARCH {
	case "arm64":
		arch = "aarch64"
	case "386":
		arch = "i386"
	}
	os_ := "linux-gnu"
	switch runtime.GOOS {
	case "darwin":
		os_ = "apple-darwin"
	case "windows":
		os_ = "windows-gnu"
	}
	return arch + "-unknown-" + os_
}

// ---------------------------------------------------------------------------
// Generating a program
// ---------------------------------------------------------------------------

// program generates the module for a sequence of top-level forms.
//
// Each form becomes a call from `main` into the runtime, in order, because a
// top-level form may define a global, print something, or capture a
// continuation that spans the rest of the file — all of which are the runtime's
// business.  A **pure procedure** among them is additionally compiled to native
// code, and the calls to it are direct; the definition still goes to the
// runtime, so that a program which looks the procedure up by name at run time
// finds it.
//
// That is the hybrid in its simplest form, and the shape of everything below:
// native where the compiler can prove a procedure is a pure function of its
// arguments, the runtime everywhere else.  The alternative — compiling whole
// forms natively — would have to answer "what does this form mean" for every
// special form, macro and library in the language, which is the interpreter's
// job and is already written.
func (g *irGen) program(forms []Value) error {
	m := g.module
	// The runtime entry points.  They are the C ABI of the RE layer.
	m.declare("void @gs_init(i32, i8**)")
	m.declare("void @gs_finish()")
	m.declare("i64 @gs_eval_source(i8*, i64, i8*)")
	m.declare("void @gs_note_native(i8*, i32)")

	var body strings.Builder
	body.WriteString("define i32 @main(i32 %argc, i8** %argv) {\n")
	body.WriteString("entry:\n")
	fmt.Fprintf(&body, "  call void @gs_init(i32 %%argc, i8** %%argv)\n")

	for i, form := range forms {
		src := WriteToString(form)
		lit := m.stringLiteral(src, fmt.Sprintf("form%d", i))
		// The source of the form, its length, and a name for error messages.
		name := m.stringLiteral(fmt.Sprintf("<top level %d>", i+1), fmt.Sprintf("name%d", i))
		fmt.Fprintf(&body, "  %s = call i64 @gs_eval_source(i8* %s, i64 %d, i8* %s)\n",
			m.reg(), lit, len(src), name)
	}
	// A pure procedure defined at the top level also gets a native body, and
	// the runtime is told about it: the count is what `--emit-llvm`'s reader
	// and the tests use to see that the hybrid happened.
	if g.native > 0 {
		fmt.Fprintf(&body, "  call void @gs_note_native(i8* null, i32 %d)\n", g.native)
	}
	body.WriteString("  call void @gs_finish()\n")
	body.WriteString("  ret i32 0\n")
	body.WriteString("}\n")
	m.body.WriteString(body.String())
	return nil
}

// stringLiteral interns a string constant and returns the global that holds it.
// A Scheme string is UTF-8 bytes with a length, so the constant carries both:
// a NUL inside a Scheme string is a character like any other, and a C string
// would stop there.
func (m *irModule) stringLiteral(s, hint string) string {
	if g, ok := m.strings[s]; ok {
		return g
	}
	name := "@." + hint
	m.strings[s] = name
	// The bytes, escaped for LLVM assembly, then a NUL so that the constant is
	// also usable as a C string when its length is not needed.
	fmt.Fprintf(&m.body, "%s = private unnamed_addr constant [%d x i8] c\"%s\\00\"\n",
		name, len(s)+1, llvmEscape(s))
	return name
}

// llvmEscape renders a Go string as the body of an LLVM string constant: the
// printable characters as themselves, everything else as \XX.
func llvmEscape(s string) string {
	var b strings.Builder
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c == '"':
			b.WriteString("\\22")
		case c == '\\':
			b.WriteString("\\5C")
		case c >= 0x20 && c < 0x7f:
			b.WriteByte(c)
		default:
			fmt.Fprintf(&b, "\\%02X", c)
		}
	}
	return b.String()
}
