;;; SPDX-License-Identifier: MIT
;;; The performance library: jobs done in Go rather than in interpreted Scheme.

(import (scheme base) (scheme write) (scheme char) (chibi test)
        (goscheme fast))

(test-begin "Fast")

;; ---------------------------------------------------------------------- order
(test-begin "Ordering")

(test '(1 2 3) (sort (list 3 1 2)))
(test '() (sort '()))
(test '(1) (sort (list 1)))
(test '(3 2 1) (sort (list 3 1 2) >))
(test '("a" "b" "c") (sort (list "b" "c" "a") string<?))
(test '(1 2 3) (sort (list 3 1 2) (lambda (a b) (< a b))))
;; A comparison the library does not know still works, through a Scheme call.
(test '(3 2 1) (sort (list 1 3 2) (lambda (a b) (> a b))))
(test '(1 2 3) (sort (list 2 3 1) <=))

(test #(1 2 3) (vector-sort (vector 3 1 2)))
(test #() (vector-sort (vector)))
(define sortable (vector 3 1 2))
(test #t (eq? sortable (sort! sortable)))
(test #(1 2 3) sortable)

(test 2 (vector-binary-search (vector 1 3 5 7) 5))
(test 0 (vector-binary-search (vector 1 3 5 7) 1))
(test 3 (vector-binary-search (vector 1 3 5 7) 7))
(test #f (vector-binary-search (vector 1 3 5 7) 4))
(test 1 (vector-binary-search (vector "a" "b" "c") "b" string<?))
(test 'not-a-procedure (guard (e (#t 'not-a-procedure)) (sort (list 1) 5)))

(test-end)

;; ------------------------------------------------------------------ sequences
(test-begin "Sequences")

(test '() (iota 0))
(test '(0 1 2) (iota 3))
(test '(10 20 30) (iota 3 10 10))
(test '(5 4 3) (iota 3 5 -1))
(test '(0 1/2 1) (iota 3 0 1/2))

(test #(3 2 1) (vector-reverse (vector 1 2 3)))
(test #() (vector-reverse (vector)))
(define v (vector 1 2 3))
(test #(3 2 1) (vector-reverse! v))
(define swapme (vector 1 2 3))
(vector-swap! swapme 0 2)
(test #(3 2 1) swapme)
(test 'out-of-range (guard (e (#t 'out-of-range)) (vector-swap! swapme 0 9)))

(test-end)

;; ------------------------------------------------------------------ selection
(test-begin "Selection")

(test '(0 2 4 6 8) (filter even? (iota 10)))
(test '() (filter even? '()))
(test '(6 7 8 9) (filter (lambda (x) (> x 5)) (iota 10)))
(test '("a" "b") (filter string? (list 1 "a" 'b "b" 2)))
(test '(2 4) (filter (lambda (x) (even? x)) (vector 1 2 3 4 5)))
(test 5 (count even? (iota 10)))
(test 0 (count even? '()))
(test 2 (count (lambda (x) (> x 7)) (iota 10)))
(test #f (any even? (list 1 3 5)))
(test #t (any even? (list 1 2 3)))
(test #t (every even? (list 2 4)))
(test #f (every even? (list 2 3)))
(test #t (every even? '()))
(define vf (vector 1 2 3 4 5 6))
(test 3 (vector-filter! even? vf))
(test 2 (vector-ref vf 0))
(test 4 (vector-ref vf 1))

(test-end)

;; ----------------------------------------------------------------- aggregates
(test-begin "Aggregates")

(test 0 (sum '()))
(test 55 (sum (iota 11)))
(test 6 (sum (vector 1 2 3)))
(test 3.5 (sum (list 1 2.5)))
(test 24 (product (list 1 2 3 4)))
(test 1 (product '()))
(test 1 (min-of (list 3 1 2)))
(test 3 (max-of (list 3 1 2)))
(test 1 (min-of (vector 3 1 2)))
(test 1/3 (min-of (list 1/3 1/2)))
(test 'empty (guard (e (#t 'empty)) (min-of '())))
(test 'empty (guard (e (#t 'empty)) (max-of (vector))))
(test 32 (vector-dot (vector 1 2 3) (vector 4 5 6)))
(test 0 (vector-dot (vector) (vector)))
(test 'lengths (guard (e (#t 'lengths)) (vector-dot (vector 1) (vector 1 2))))
(test 'not-a-number (guard (e (#t 'not-a-number)) (sum (list 1 'x))))

(test-end)

;; -------------------------------------------------------------------- strings
(test-begin "Strings")

(test '("a" "b" "c") (string-split "a,b,c" ","))
(test '("abc") (string-split "abc" ","))
;; With no separator the string is split into characters.
(test '("a" " " "b") (string-split "a b"))
(test '("a" "b" "c") (string-split "abc" ""))
(test "a-b" (string-join (list "a" "b") "-"))
(test "ab" (string-join (list "a" "b")))
(test "" (string-join '() "-"))
(test 6 (string-contains "hello world" "world"))
(test #f (string-contains "hello" "zz"))
(test 0 (string-contains "hello" ""))
(test 2 (string-index "hello" #\l))
(test #f (string-index "hello" #\z))
(test #t (string-prefix? "hello" "he"))
(test #f (string-prefix? "hello" "lo"))
(test #t (string-suffix? "hello" "lo"))
(test "x" (string-trim "  x  "))
(test "a" (string-trim "xxaxx" "x"))
(test "x  " (string-trim-left "  x  "))
(test "  x" (string-trim-right "  x  "))
(test "a+b+c" (string-replace "a-b-c" "-" "+"))
(test "abc" (string-replace "abc" "z" "+"))
(test "007" (string-pad-left "7" 3 #\0))
(test "7  " (string-pad-right "7" 3))
(test "777" (string-pad-left "777" 1))
(test 'empty-needle (guard (e (#t 'empty-needle)) (string-replace "abc" "" "x")))

(test-end)

;; ---------------------------------------------------------------------- bytes
(test-begin "Bytes")

;; The digest of "abc" is a fixed value, so this checks the hash itself.
(test "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad" (sha256 "abc"))
(test "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" (sha256 ""))
(test (sha256 "abc") (sha256 (string->utf8 "abc")))
(test 'bad-hash (guard (e (#t 'bad-hash)) (sha256 5)))
(test "01ff" (hex-encode #u8(1 255)))
(test #u8(1 255) (hex-decode "01ff"))
(test #u8(1 255) (hex-decode (hex-encode #u8(1 255))))
(test 'bad-hex (guard (e (#t 'bad-hex)) (hex-decode "zz")))
(test "aGk=" (base64-encode #u8(104 105)))
(test #u8(104 105) (base64-decode "aGk="))
(test #u8(104 105) (base64-decode (base64-encode #u8(104 105))))
(test 'bad-base64 (guard (e (#t 'bad-base64)) (base64-decode "!!!")))
(test 8 (bytevector-length (random-bytes 8)))
(test 0 (bytevector-length (random-bytes 0)))

(test-end)


;; ---------------------------------------------------------------------- lists
(test-begin "Lists")

(test 3 (last '(1 2 3)))
(test 3 (last #(1 2 3)))
(test 'empty (guard (e (#t 'empty)) (last '())))

(test '(1 2) (take 2 '(1 2 3)))
(test '() (take 0 '(1 2 3)))
(test '(1 2 3) (take 3 '(1 2 3)))
(test '(3) (drop 2 '(1 2 3)))
(test '() (drop 3 '(1 2 3)))
(test '(2 3) (take-right 2 '(1 2 3)))
(test '(1) (drop-right 2 '(1 2 3)))
(test '() (take-right 0 '(1 2 3)))
(test '(1 2 3) (drop-right 0 '(1 2 3)))
(test 'too-short (guard (e (#t 'too-short)) (take 4 '(1 2 3))))
(test 'too-short (guard (e (#t 'too-short)) (drop 4 '(1 2 3))))
(test 'too-short (guard (e (#t 'too-short)) (take-right 4 '(1 2 3))))
(test 'too-short (guard (e (#t 'too-short)) (drop-right 4 '(1 2 3))))

(call-with-values (lambda () (split-at 1 '(1 2 3)))
  (lambda (a b) (test '(1) a) (test '(2 3) b)))
(call-with-values (lambda () (split-at 0 '(1)))
  (lambda (a b) (test '() a) (test '(1) b)))
(call-with-values (lambda () (split-at 1 '(1)))
  (lambda (a b) (test '(1) a) (test '() b)))

(test 2 (list-index even? '(1 3 4 5)))
(test 1 (list-index odd? '(2 3 4)))
(test #f (list-index even? '(1 3 5)))
(test 0 (list-index (lambda (x) (> x 0)) '(1 2)))
(test 1 (list-index (lambda (x) (> x 0)) '(-1 2)))
(test #f (list-index (lambda (x) (> x 0)) '(-1 -2)))

(test 4 (find even? '(1 3 4)))
(test #f (find even? '(1 3 5)))
(test 2 (find (lambda (x) (= 0 (modulo x 2))) '(1 3 2)))

(test '(1 3) (filter-not even? '(1 2 3 4)))
(test '() (filter-not even? '(2 4)))
(test '("a" "c") (delete "b" '("a" "b" "c") string=?))
(test '(1 3) (delete 2 '(1 2 2 3)))
(test '() (delete 1 '()))

(test '(1 2 3) (delete-duplicates '(1 2 1 3 2)))
(test '("a" "b") (delete-duplicates '("a" "b" "a")))
(test '((1) (2)) (delete-duplicates '((1) (2) (1))))
(test '(1 2) (delete-duplicates '(1 1.0 2) =))
(test '() (delete-duplicates '()))

(call-with-values (lambda () (partition even? '(1 2 3 4)))
  (lambda (a b) (test '(2 4) a) (test '(1 3) b)))
(call-with-values (lambda () (partition even? '()))
  (lambda (a b) (test '() a) (test '() b)))

(test '(1 2 3 4 5 6) (flatten '(1 (2 (3 4)) #(5 6))))
(test '(1) (flatten '(1)))
(test '() (flatten '()))

(test '((1 a) (2 b)) (zip '(1 2 3) '(a b)))
(test '((1 a b)) (zip '(1) '(a) '(b)))
(test '() (zip '() '(1)))
(test '((1 2) (a b)) (unzip '((1 a) (2 b))))
(test '() (unzip '()))

(test '((1 2) (3 4) (5)) (chunk '(1 2 3 4 5) 2))
(test '() (chunk '() 2))
(test 'bad-chunk (guard (e (#t 'bad-chunk)) (chunk '(1) 0)))

(test '((a . 1) (b . 9)) (assoc-set '((a . 1) (b . 2)) 'b 9))
(test '((a . 1) (c . 3)) (assoc-set '((a . 1)) 'c 3))
(test '((c . 3)) (assoc-set '() 'c 3))
(test '((a . 1) (z . 0)) (assoc-set '((a . 1)) 'z 0))
(test '((("a") . 1)) (assoc-set '() '("a") 1))

(test 10 (fold-left + 0 '(1 2 3 4)))
(test 24 (fold-left * 1 '(1 2 3 4)))
(test 9 (fold-left max 0 '(3 9 2)))
(test 2 (fold-left min 9 '(3 2 8)))
(test 6 (fold-left (lambda (a b) (+ a b)) 0 '(1 2 3)))
(test 0 (fold-left + 0 '()))
(test 2 (fold-right - 0 '(1 2 3)))
(test '(1 2 3) (fold-right cons '() '(1 2 3)))
(test -6 (fold-left - 0 '(1 2 3)))

(test '("a" "bb" "ccc") (sort-by string-length '("ccc" "a" "bb")))
(test '("ccc" "bb" "a") (sort-by string-length '("ccc" "a" "bb") >))
(test '(3 2 1) (sort-by - '(1 3 2)))
(test #(3 2 1) (vector-sort-by - #(1 3 2)))
(test #(1 2 3) (vector-sort-by (lambda (x) x) #(3 1 2)))

(test-end)

;; ------------------------------------------------------------------- vectors
(test-begin "Vector batch")

(test #(5 6 7) (vector-iota 3 5))
(test #(0 2 4) (vector-iota 3 0 2))
(test #() (vector-iota 0))
(test #(1 2) (vector-take 2 #(1 2 3)))
(test #(3) (vector-drop 2 #(1 2 3)))
(test #() (vector-take 0 #(1 2 3)))
(test 'too-long (guard (e (#t 'too-long)) (vector-take 5 #(1))))
(test 'too-long (guard (e (#t 'too-long)) (vector-drop 5 #(1))))
(test #(1 2 3) (vector-concat (list #(1 2) #(3))))
(test #() (vector-concat '()))
(test 'bad-concat (guard (e (#t 'bad-concat)) (vector-concat (list #(1) 2))))

(test '(0 1 2 3 4) (range 0 5))
(test '(5 3 1) (range 5 0 -2))
(test '() (range 0 0))
(test '() (range 5 0))
(test '(1 3) (range 1 4 2))
(test '(1 3/2 2) (range 1 5/2 1/2))
(test 'bad-step (guard (e (#t 'bad-step)) (range 0 5 0)))

(test #(11 22) (vector-add #(1 2) #(10 20)))
(test #(-9 -18) (vector-sub #(1 2) #(10 20)))
(test #(3 6) (vector-scale #(1 2) 3))
(test #(3 8) (vector-mul #(1 2) #(3 4)))
(test #(1/4 1/4) (vector-div #(1 2) #(4 8)))
(test #(-1 2) (vector-negate #(1 -2)))
(test #(1 2) (vector-abs #(1 -2)))
(test 5.0 (vector-norm #(3 4)))
(test 0.0 (vector-norm #()))
(test #(0 5 10) (vector-clamp #(-1 5 15) 0 10))
(test #(1 3 6) (vector-prefix-sum #(1 2 3)))
(test #() (vector-prefix-sum #()))
(test 'bad-len (guard (e (#t 'bad-len)) (vector-add #(1) #(1 2))))
(test 'bad-len (guard (e (#t 'bad-len)) (vector-mul #(1) #(1 2))))

(test 1 (vector-argmin #(3 1 2)))
(test 0 (vector-argmax #(3 1 2)))
(test 1 (vector-argmax #(1 3 2)))
(test 1 (vector-argmin #(1 3 2) >))
(test 'empty-arg (guard (e (#t 'empty-arg)) (vector-argmin #())))

(test 1 (vector-index-of #(1 2 3) 2))
(test #f (vector-index-of #(1 2 3) 9))
(test 1 (vector-index-of #("a" "b") "b" string=?))
(test #f (vector-index-of #(1 2) 1.0))
(test 0 (vector-index-of #(1 2) 1.0 =))
(test 1 (vector-index-of #(2.0 1) 1 =))

(test '(#(1 2) #(3 4) #(5)) (vector-chunk #(1 2 3 4 5) 2))
(test '() (vector-chunk #() 3))
(call-with-values (lambda () (vector-partition even? #(1 2 3 4)))
  (lambda (a b) (test #(2 4) a) (test #(1 3) b)))

(test 2 (vector-binary-search-insert #(1 3 5) 4))
(test 1 (vector-binary-search-insert #(1 3 5) 3))
(test 0 (vector-binary-search-insert #(1 3 5) 0))
(test 3 (vector-binary-search-insert #(1 3 5) 9))
(test 2 (vector-binary-search-insert #("a" "c" "e") "d" string<?))
(test 0 (vector-binary-search-insert #() 1))

(test #t (vector-equal? #(1 2) #(1 2)))
(test #f (vector-equal? #(1 2) #(1 3)))
(test #f (vector-equal? #(1 2) #(1 2 3)))
(test #t (vector-equal? #()))
(test #t (vector-equal? #(1 2) #(1 2) #(1 2)))
(test #f (vector-equal? #(1 2) #(1 2) #(9)))

(test -1 (vector-compare #(1 2) #(1 3)))
(test 1 (vector-compare #(1 3) #(1 2)))
(test 0 (vector-compare #(1 2) #(1 2)))
(test -1 (vector-compare #(1) #(1 2)))
(test 1 (vector-compare #(1 2) #(1)))
(test 1 (vector-compare #("b") #("a") string<?))
(test -1 (vector-compare #("a") #("b") string<?))

(define batch1 (vector 1 2))
(test #t (eq? batch1 (vector-add! batch1 #(10 20))))
(test #(11 22) batch1)
(define batch2 (vector 1 2))
(vector-sub! batch2 #(10 20))
(test #(-9 -18) batch2)
(define batch3 (vector 1 2))
(vector-mul! batch3 #(3 4))
(test #(3 8) batch3)
(define batch4 (vector 1 2))
(vector-div! batch4 #(4 8))
(test #(1/4 1/4) batch4)
(define batch5 (vector 1 2))
(vector-scale! batch5 10)
(test #(10 20) batch5)
(define batch6 (vector 1 -2))
(vector-negate! batch6)
(test #(-1 2) batch6)
(define batch7 (vector 1 -2))
(vector-abs! batch7)
(test #(1 2) batch7)
(define batch8 (vector -1 5 15))
(vector-clamp! batch8 0 10)
(test #(0 5 10) batch8)

(test-end)

;; ---------------------------------------------------------------- statistics
(test-begin "Statistics")

(test 2 (mean '(1 2 3)))
(test 3/2 (mean '(1 2)))
(test 5/2 (mean #(1 2 3 4)))
(test 0 (mean '(0)))
(test 'empty-mean (guard (e (#t 'empty-mean)) (mean '())))

(test 2 (median '(1 3 2)))
(test 5/2 (median '(1 2 3 4)))
(test 3 (median '(1 2 3 4 5)))
(test -3 (median '(-1 -5 -3)))
(test 'empty-median (guard (e (#t 'empty-median)) (median #())))

(test 3 (percentile '(1 2 3 4 5) 50))
(test 5 (percentile '(1 2 3 4 5) 100))
(test 1 (percentile '(1 2 3 4 5) 0))
(test 1 (percentile '(1 2 3 4 5) 1))
(test 'bad-percentile (guard (e (#t 'bad-percentile)) (percentile '(1 2) 101)))

(test #t (< (abs (- (variance '(1 2 3)) 2/3)) 1e-12))
(test #t (< (abs (- (variance '(2 2 2)) 0)) 1e-12))
(test #t (< (abs (- (stddev '(1 2 3)) 0.816496580927726)) 1e-12))
(test #t (< (abs (- (stddev '(2 2 2)) 0)) 1e-12))
(test 'empty-variance (guard (e (#t 'empty-variance)) (variance '())))

(test 2 (mode '(1 2 2 3)))
(test 1 (mode '(1 1 2 2)))
(test "b" (mode '("a" "b" "b")))
(test 'empty-mode (guard (e (#t 'empty-mode)) (mode '())))

(test-end)

;; -------------------------------------------------------------- number theory
(test-begin "Number theory")

(test 8 (bit-and 12 10))
(test 14 (bit-or 12 10))
(test 6 (bit-xor 12 10))
(test 8 (bit-and 12 10 14))
(test -1 (bit-and))
(test 0 (bit-or))
(test 0 (bit-xor))
(test -1 (bit-not 0))
(test 0 (bit-not -1))
(test 5 (bit-not -6))
(test 1024 (bit-shift 1 10))
(test 32 (bit-shift 1024 -5))
(test -1024 (bit-shift -1 10))
(test 101 (integer-length (bit-shift 1 100)))
(test 8 (bit-count 255))
(test 1 (bit-count 1))
(test 0 (bit-count 0))
(test 3 (bit-count 7))
(test 8 (integer-length 255))
(test 0 (integer-length 0))
(test 1 (integer-length 1))
(test 'bad-bit (guard (e (#t 'bad-bit)) (bit-and 1.5)))

(test 24 (expt-mod 2 10 1000))
(test 1 (expt-mod 3 0 7))
(test 2 (expt-mod 2 100 7))
(test 'neg-exp (guard (e (#t 'neg-exp)) (expt-mod 2 -1 7)))
(test 'bad-mod (guard (e (#t 'bad-mod)) (expt-mod 2 3 0)))

(test 4 (isqrt 17))
(test 5 (isqrt 25))
(test 0 (isqrt 0))
(test 1 (isqrt 1))
(test 'neg-isqrt (guard (e (#t 'neg-isqrt)) (isqrt -1)))

(test #t (prime? 2))
(test #t (prime? 97))
(test #f (prime? 91))
(test #f (prime? 1))
(test #f (prime? 0))
(test #f (prime? -7))
(test #t (prime? 1000003))
(test #f (prime? 1000001))

(test '(2 3 5 7 11 13 17 19) (primes 20))
(test '() (primes 2))
(test '() (primes 0))

(test '(2 2 2 3 3 5) (factor 360))
(test '(97) (factor 97))
(test '() (factor 1))
(test '(1000003) (factor 1000003))
(test '(2) (factor 2))
(test '(2 3 3 5 3607 3803) (factor 1234567890))
(test 'bad-factor (guard (e (#t 'bad-factor)) (factor 0)))

(test 10 (clamp 15 0 10))
(test 0 (clamp -5 0 10))
(test 5 (clamp 5 0 10))
(test 'bad-clamp (guard (e (#t 'bad-clamp)) (clamp 5 10 0)))

(test -1 (sign -7))
(test 0 (sign 0))
(test 1 (sign 7))
(test 'bad-sign (guard (e (#t 'bad-sign)) (sign "x")))

(test-end)

;; ----------------------------------------------------------------------- text
(test-begin "Text")

(test "cba" (string-reverse "abc"))
(test "" (string-reverse ""))
(test "ababab" (string-repeat "ab" 3))
(test "" (string-repeat "ab" 0))
(test 3 (string-count "banana" #\a))
(test 2 (string-count "aaaa" "aa"))
(test 0 (string-count "abc" #\z))
(test 5 (string-last-index "banana" #\a))
(test 3 (string-last-index "banana" "an"))
(test #f (string-last-index "abc" #\z))
(test 2 (string-index-from "banana" #\a 2))
(test 3 (string-index-from "banana" "na" 3))
(test #f (string-index-from "banana" #\a 6))
(test '(0 2) (string-find-all "aaaa" "aa"))
(test '(1 3) (string-find-all "abab" "b"))
(test '() (string-find-all "abc" ""))

(test '("a" "b") (string-fields "  a \t b "))
(test '() (string-fields "   "))
(test '() (string-fields ""))
(test '("a" "b") (string-lines "a\nb\n"))
(test '("a" "b") (string-lines "a\r\nb\r\n"))
(test '("a" "" "b") (string-lines "a\n\nb"))
(test '("a") (string-lines "a"))

(test '("ab" "cd" "ef") (string-chunk "abcdef" 2))
(test '("abc") (string-chunk "abc" 5))
(test '() (string-chunk "" 2))
(test 'bad-chunk (guard (e (#t 'bad-chunk)) (string-chunk "ab" 0)))

(test "abc" (string-sort "cba"))
(test "aabc" (string-sort "caba"))
(test "" (string-sort ""))

(test "he" (string-take "hello" 2))
(test "llo" (string-drop "hello" 2))
(test "hello" (string-take "hello" 5))
(test "" (string-drop "hello" 5))
(test 'too-long (guard (e (#t 'too-long)) (string-take "hi" 5)))
(test 'too-long (guard (e (#t 'too-long)) (string-drop "hi" 5)))

(test "--ab--" (string-pad-center "ab" 6 #\-))
(test " ab " (string-pad-center "ab" 4))
(test "abcd" (string-pad-center "abcd" 2))

(test "AB" (string-upper "aB"))
(test "ab" (string-lower "aB"))
(test "Hello World" (string-titlecase "hello WORLD"))
(test "Ada Lovelace" (string-titlecase "ada lovelace"))
(test "Ada 3 X" (string-titlecase "ada 3 x"))

(test #t (string-blank? "  \t "))
(test #t (string-blank? ""))
(test #f (string-blank? " x "))
(test #t (string-empty? ""))
(test #f (string-empty? " "))
(test #t (string-prefix-ci? "Hello" "he"))
(test #f (string-prefix-ci? "Hello" "xx"))
(test #t (string-suffix-ci? "Hello" "LO"))
(test #f (string-suffix-ci? "Hello" "xx"))

(test "baa" (string-replace-first "aaa" "a" "b"))
(test "axc" (string-replace-first "abc" "b" "x"))
(test 'empty-needle (guard (e (#t 'empty-needle)) (string-replace-first "abc" "" "x")))
(test "line" (string-chomp "line\n"))
(test "line" (string-chomp "line\r\n"))
(test "line" (string-chomp "line"))
(test "" (string-chomp "\n"))

(test #t (string-integer? "42"))
(test #t (string-integer? "-42"))
(test #t (string-integer? "+42"))
(test #f (string-integer? "4.2"))
(test #f (string-integer? ""))
(test #f (string-integer? " 42"))
(test #t (string-integer? "ff" 16))
(test #f (string-integer? "ff"))
(test 'bad-radix (guard (e (#t 'bad-radix)) (string-integer? "1" 99)))

(test 6 (string-byte-length "héllo"))
(test 5 (string-length "héllo"))
(test 3 (string-byte-length "abc"))

(test-end)

;; -------------------------------------------------------------- bytes, hashes
(test-begin "Bytes and hashes")

(test "a9993e364706816aba3e25717850c26c9cd0d89d" (sha1 "abc"))
(test "900150983cd24fb0d6963f7d28e17f72" (md5 "abc"))
(test "ddaf35a193617abacc417349ae20413112e6fa4e89a97ea20a9eeee64b55d39a2192992a274fc1a836ba3c23a3feebbd454d4423643ce80e2a9ac94fa54ca49f"
      (sha512 "abc"))
(test (sha1 "abc") (sha1 (string->utf8 "abc")))
;; RFC 4231, test case 1.
(test "b0344c61d8db38535ca8afceaf0bf12b881dc200c9833da726e9376c2e32cff7"
      (hmac-sha256 (make-bytevector 20 11) "Hi There"))
(test 891568578 (crc32 "abc"))
(test 0 (crc32 ""))

(test "NBUQ====" (base32-encode #u8(104 105)))
(test #u8(104 105) (base32-decode "NBUQ===="))
(test #u8(104 105) (base32-decode "nbuq===="))
(test 'bad-base32 (guard (e (#t 'bad-base32)) (base32-decode "!!")))
(test "-_8=" (base64url-encode #u8(251 255)))
(test #u8(251 255) (base64url-decode "-_8="))
(test #u8(251 255) (base64url-decode "-_8"))

(test #u8(254 253 252) (bytes-xor #u8(1 2 3) #u8(255)))
(test #u8(0 0 0) (bytes-xor #u8(1 2 3) #u8(1 2 3)))
(test #u8(1 2 3) (bytes-xor (bytes-xor #u8(1 2 3) #u8(9)) #u8(9)))
(test 'empty-mask (guard (e (#t 'empty-mask)) (bytes-xor #u8(1) #u8())))
(test #u8(8) (bytes-and #u8(12) #u8(10)))
(test #u8(14) (bytes-or #u8(12) #u8(10)))
(test #u8(255) (bytes-not #u8(0)))
(test #u8(3 2 1) (bytes-reverse #u8(1 2 3)))
(test #u8() (bytes-reverse #u8()))
(test 1 (bytes-index #u8(1 2 3) #u8(2 3)))
(test #f (bytes-index #u8(1 2 3) #u8(3 2)))
(test 0 (bytes-index #u8(1 2 3) #u8()))
(test 'bad-len (guard (e (#t 'bad-len)) (bytes-and #u8(1) #u8(1 2))))

(define fillable (bytevector 1 2 3 4))
(test #t (eq? fillable (bytevector-fill! fillable 9 1 3)))
(test #u8(1 9 9 4) fillable)
(define fillable2 (bytevector 1 2 3))
(bytevector-fill! fillable2 7)
(test #u8(7 7 7) fillable2)
(define fillable3 (bytevector 1 2 3 4))
(bytevector-fill! fillable3 0 2)
(test #u8(1 2 0 0) fillable3)
(test 'bad-range (guard (e (#t 'bad-range)) (bytevector-fill! (bytevector 1) 0 2 2)))

(test #u8(1 255) (vector->bytevector #(1 255)))
(test #(1 255) (bytevector->vector #u8(1 255)))
(test 'bad-byte (guard (e (#t 'bad-byte)) (vector->bytevector #(256))))
(test 'bad-vector (guard (e (#t 'bad-vector)) (vector->bytevector #(1.5))))

(test-end)

;; --------------------------------------------------------------------- random
(test-begin "Random")

(test #t (< (random-int 10) 10))
(test #t (>= (random-int 1) 0))
(test 'bad-bound (guard (e (#t 'bad-bound)) (random-int 0)))
(test #t (and (>= (random-float) 0) (< (random-float) 1)))
(test #t (if (memv (random-choice '(1 2 3)) '(1 2 3)) #t #f))
(test 'bad-choice (guard (e (#t 'bad-choice)) (random-choice '())))
(test 8 (string-length (random-string 8)))
(test 0 (string-length (random-string 0)))
(test 0 (string-length (string-trim (random-string 20 "ab") "ab")))
(test 'bad-alphabet (guard (e (#t 'bad-alphabet)) (random-string 4 "")))
(test 36 (string-length (uuid)))
(test 5 (length (string-split (uuid) "-")))
(test #f (equal? (uuid) (uuid)))

(test 5 (length (shuffle '(1 2 3 4 5))))
(test #t (every (lambda (v) (memv v (shuffle '(1 2 3 4 5)))) '(1 2 3 4 5)))
(test '() (shuffle '()))
(test 'bad-shuffle (guard (e (#t 'bad-shuffle)) (shuffle 5)))
(define shuffled (vector 1 2 3 4 5))
(test #t (eq? shuffled (vector-shuffle! shuffled)))
(test 5 (vector-length shuffled))
(test #t (every (lambda (v) (memv v (vector->list shuffled))) '(1 2 3 4 5)))
(test 2 (vector-length (vector-sample #(1 2 3 4) 2)))
(test 0 (vector-length (vector-sample #(1 2) 0)))
(test 'too-many (guard (e (#t 'too-many)) (vector-sample #(1 2) 3)))

(test-end)

(test-end)
