;;; SPDX-License-Identifier: MIT
(define (fact n) (if (= n 0) 1 (* n (fact (- n 1)))))
(display (fact 20)) (newline)
(display (fact 50)) (newline)
(define (loop i acc) (if (= i 0) acc (loop (- i 1) (+ acc 1))))
(display (loop 1000000 0)) (newline)
(display (let loop ((i 0) (acc '())) (if (= i 5) (reverse acc) (loop (+ i 1) (cons i acc))))) (newline)
(display (map (lambda (x) (* x x)) '(1 2 3 4))) (newline)
(display (call/cc (lambda (k) (+ 1 (k 42))))) (newline)
(display `(1 ,(+ 1 1) ,@(list 3 4) 5)) (newline)
(define-syntax swap! (syntax-rules () ((_ a b) (let ((tmp a)) (set! a b) (set! b tmp)))))
(define x 1) (define y 2) (swap! x y) (display (list x y)) (newline)
(display (vector-map + #(1 2 3) #(10 20 30))) (newline)
(display (string-map char-upcase "hello")) (newline)
(display (assoc 2 '((1 a) (2 b)))) (newline)
(display (exact->inexact 1/3)) (newline)
(display (number->string 255 16)) (newline)
(display (list (quotient 7 2) (modulo -7 2) (remainder -7 2))) (newline)
(display (call/cc (lambda (k)
  (with-exception-handler (lambda (e) (k (list 'caught e))) (lambda () (raise 'boom)))))) (newline)
(display (with-exception-handler (lambda (e) 42) (lambda () (+ 1 (raise-continuable 'x))))) (newline)
(display (guard (e (#t (list 'guarded e))) (error "bad" 1 2))) (newline)
(define-record-type point (make-point x y) point? (x point-x set-point-x!) (y point-y))
(define p (make-point 1 2))
(display (list (point? p) (point-x p) (point-y p))) (newline)
(set-point-x! p 9) (display (point-x p)) (newline)
(display (force (delay (+ 1 2)))) (newline)
(define param (make-parameter 10))
(display (list (param) (parameterize ((param 20)) (param)) (param))) (newline)
