;;; SPDX-License-Identifier: MIT
;;; SRFI-128, comparators.  The hash values themselves are an implementation
;;; detail, so what is tested here are their properties: exactness, the bound,
;;; and that equal values hash alike.

(import (scheme base) (scheme write) (chibi test) (srfi 128))

(test-begin "SRFI 128")

;; ------------------------------------------------------------ constructing
(define number-comparator (make-comparator number? = < number-hash))
(test #t (comparator? number-comparator))
(test #f (comparator? 5))
(test #f (comparator? '(1)))
(test #t (comparator-ordered? number-comparator))
(test #t (comparator-hashable? number-comparator))
(test #t (procedure? (comparator-type-test-predicate number-comparator)))
(test #t (procedure? (comparator-equality-predicate number-comparator)))
(test #t (procedure? (comparator-ordering-predicate number-comparator)))
(test #t (procedure? (comparator-hash-function number-comparator)))
(define unordered (make-comparator (lambda (x) #t) equal? #f #f))
(test #f (comparator-ordered? unordered))
(test #f (comparator-hashable? unordered))
(test #f (comparator-ordering-predicate unordered))
(test #f (comparator-hash-function unordered))
(test 'not-a-procedure (guard (e (#t 'not-a-procedure)) (make-comparator number? 5 < number-hash)))
;; A #f type test accepts anything, and a #f equality means eqv?.
(define loose (make-comparator #f #f #f #f))
(test #t (comparator-test-type loose "anything"))
(test #t (=? loose 1 1))
(test #f (=? loose 1 1.0))
(test #t (=? loose 'a 'a))

(test #t (comparator-test-type number-comparator 5))
(test #f (comparator-test-type number-comparator "x"))
(test #t (comparator-check-type number-comparator 5))
(test 'bad-type (guard (e (#t 'bad-type)) (comparator-check-type number-comparator "x")))

;; ------------------------------------------------------------- operations
(test #t (=? number-comparator 1 1))
(test #t (=? number-comparator 1 1 1))
(test #t (=? number-comparator 1))
(test #f (=? number-comparator 1 2))
(test #f (=? number-comparator 1 1 2))
(test #t (<? number-comparator 1 2))
(test #t (<? number-comparator 1 2 3))
(test #f (<? number-comparator 1 3 2))
(test #t (>? number-comparator 3 2))
(test #t (<=? number-comparator 1 1))
(test #t (<=? number-comparator 1 2))
(test #f (<=? number-comparator 2 1))
(test #t (>=? number-comparator 2 2))
(test #t (>=? number-comparator 3 2))
(test #f (>=? number-comparator 1 2))
(test 'no-ordering (guard (e (#t 'no-ordering)) (<? unordered 1 2)))

(test 'less (comparator-if<=> number-comparator 1 2 'less 'equal 'greater))
(test 'equal (comparator-if<=> number-comparator 2 2 'less 'equal 'greater))
(test 'greater (comparator-if<=> number-comparator 3 2 'less 'equal 'greater))
(test 'lt (comparator-if<=> number-comparator 1 2 (lambda () 'lt) (lambda () 'eq) (lambda () 'gt)))
(test 'eq (comparator-if<=> number-comparator 2 2 (lambda () 'lt) (lambda () 'eq) (lambda () 'gt)))
(test 'gt (comparator-if<=> number-comparator 3 2 (lambda () 'lt) (lambda () 'eq) (lambda () 'gt)))

;; ------------------------------------------------------------ ready-made
(test #t (comparator? (make-eq-comparator)))
(test #t (comparator? (make-eqv-comparator)))
(test #t (comparator? (make-equal-comparator)))
(test #t (=? (make-eq-comparator) 'a 'a))
(test #f (=? (make-eq-comparator) "a" "a"))
(test #f (=? (make-eqv-comparator) 1 1.0))
(test #t (=? (make-equal-comparator) "a" "a"))
(test #t (=? (make-equal-comparator) '(1 2) '(1 2)))
(test #f (comparator-ordered? (make-equal-comparator)))

(define default (make-default-comparator))
(test #t (comparator? default))
(test #t (comparator-ordered? default))
(test #t (comparator-hashable? default))
(test #t (comparator-test-type default '(1 2)))
(test #t (=? default "a" "a"))
(test #f (=? default 1 1.0))
(test #t (<? default 1 2))
(test #t (>? default 2 1))
(test #t (<? default "a" "b"))
(test #t (<? default #\a #\b))
(test #t (<? default 'a 'b))
(test #t (<? default #f #t))
(test #t (<=? default 1 1))
(test 'mixed (guard (e (#t 'mixed)) (<? default 1 "a")))
(test 'mixed (guard (e (#t 'mixed)) (<? default '(1) '(2))))

;; ---------------------------------------------------------------- hashing
(define (in-range? n) (and (exact-integer? n) (<= 0 n) (< n (hash-bound))))
(test #t (in-range? (default-hash "x")))
(test #t (in-range? (default-hash '(1 2))))
(test #t (in-range? (string-hash "abc")))
(test #t (in-range? (symbol-hash 'abc)))
(test #t (in-range? (char-hash #\a)))
(test #t (in-range? (boolean-hash #t)))
(test #t (in-range? (number-hash 1/2)))
(test #t (in-range? (number-hash 1.5)))
(test #t (= (default-hash "x") (default-hash "x")))
(test #t (= (string-hash "abc") (string-hash (string-append "ab" "c"))))
(test #t (= (symbol-hash 'abc) (symbol-hash (string->symbol "abc"))))
(test #t (= (char-hash #\a) (char-hash #\a)))
(test #t (= (boolean-hash #f) (boolean-hash #f)))
(test #t (= (number-hash 2) (number-hash 2)))
;; The case-insensitive hashes fold case first; the sensitive ones do not.
(test #t (= (string-ci-hash "ABC") (string-ci-hash "abc")))
(test #t (= (char-ci-hash #\A) (char-ci-hash #\a)))
(test #f (= (string-hash "ABC") (string-hash "abc")))
(test #f (= (char-hash #\A) (char-hash #\a)))
;; Wrong types are errors.
(test 'bad (guard (e (#t 'bad)) (string-hash 5)))
(test 'bad (guard (e (#t 'bad)) (char-hash "x")))
(test 'bad (guard (e (#t 'bad)) (symbol-hash "x")))
(test 'bad (guard (e (#t 'bad)) (boolean-hash 1)))
(test 'bad (guard (e (#t 'bad)) (number-hash "x")))
;; The two parameters are R7RS parameters, so parameterize reaches them.
(test #t (parameterize ((hash-bound 10)) (< (default-hash "x") 10)))
(test #f (= (default-hash "x")
            (parameterize ((hash-salt 12345)) (default-hash "x"))))
(test #t (parameterize ((hash-bound 1)) (= 0 (default-hash "x"))))

(test-end)
