;;; SPDX-License-Identifier: MIT
;;; SRFI-1, the list library, with (goscheme fast) imported as well: the two
;;; libraries share sixteen bindings, so this suite also proves that importing
;;; both leaves them agreeing.

(import (scheme base) (scheme write) (scheme char) (chibi test)
        (srfi 1) (goscheme fast))

(test-begin "SRFI 1")

;; ------------------------------------------------------------ constructors
(test-begin "Constructors")

(test '(1 2 . 3) (cons* 1 2 3))
(test 1 (cons* 1))
(test '(1 2 3 4) (cons* 1 2 '(3 4)))
(test 5 (cons* 5))
(test '(2 . 1) (xcons 1 2))
(test '(0 1 4 9) (list-tabulate 4 (lambda (i) (* i i))))
(test '() (list-tabulate 0 (lambda (i) i)))
(test '(a b) (list-tabulate 2 (lambda (i) (if (= i 0) 'a 'b))))
(test '(x x) (make-list 2 'x))
(test 3 (length (make-list 3)))
(test-end)

;; -------------------------------------------------------------- predicates
(test-begin "Predicates")

(test #t (proper-list? '(1 2 3)))
(test #t (proper-list? '()))
(test #f (proper-list? '(1 . 2)))
(test #f (proper-list? (circular-list 1 2)))
(test #t (circular-list? (circular-list 1 2 3)))
(test #f (circular-list? '(1 2 3)))
(test #f (circular-list? 5))
(test #t (dotted-list? '(1 . 2)))
(test #f (dotted-list? '(1 2)))
(test #f (dotted-list? (circular-list 1)))
(test #t (not-pair? '()))
(test #t (not-pair? 5))
(test #f (not-pair? '(1)))
(test #t (null-list? '()))
(test #f (null-list? '(1)))
(test 'not-a-list (guard (e (#t 'not-a-list)) (null-list? 5)))
(test 3 (length+ '(1 2 3)))
(test 0 (length+ '()))
(test #f (length+ (circular-list 1 2 3)))
(test 'not-a-list (guard (e (#t 'not-a-list)) (length+ 5)))
(test 2 (list-ref (circular-list 1 2 3) 7))

(test #t (list= = '(1 2) '(1 2)))
(test #t (list= = '() '()))
(test #t (list= = '(1 2) '(1 2) '(1 2)))
(test #f (list= = '(1 2) '(1 3)))
(test #f (list= = '(1) '(1 2)))
(test #t (list= string-ci=? '("a") '("A")))
(test-end)

;; --------------------------------------------------------------- selectors
(test-begin "Selectors")

(test 1 (first '(1 2 3)))
(test 2 (second '(1 2 3)))
(test 3 (third '(1 2 3)))
(test 4 (fourth '(1 2 3 4)))
(test 5 (fifth '(1 2 3 4 5)))
(test 10 (tenth '(1 2 3 4 5 6 7 8 9 10)))
(test 'too-short (guard (e (#t 'too-short)) (third '(1 2))))
(test '(3) (last-pair '(1 2 3)))
(test '(1) (last-pair '(1)))
(test 'empty (guard (e (#t 'empty)) (last-pair '())))
(call-with-values (lambda () (car+cdr '(1 2 3)))
  (lambda (a d) (test 1 a) (test '(2 3) d)))
(test '(1 2) (take 2 '(1 2 3)))
(test '(3) (drop 2 '(1 2 3)))
(test '(2 3) (take-right 2 '(1 2 3)))
(test '(1) (drop-right 2 '(1 2 3)))
(call-with-values (lambda () (split-at 1 '(1 2 3)))
  (lambda (a b) (test '(1) a) (test '(2 3) b)))
(test 3 (last '(1 2 3)))
(test '(1 2) (take! 2 '(1 2 3)))
(test '(1) (drop-right! 2 '(1 2 3)))
(test-end)

;; -------------------------------------------------------------------- misc
(test-begin "Misc")

(test '(3 2 1 4 5) (append-reverse '(1 2 3) '(4 5)))
(test '(1 2 3) (append-reverse '() '(1 2 3)))
(test '(1 2 3) (concatenate '((1 2) (3) ())))
(test '() (concatenate '()))
(test '(1 2 3) (concatenate! (list (list 1 2) (list 3))))
(define rev-list (list 1 2 3))
(test '(3 2 1) (reverse! rev-list))
(define app-a (list 1 2))
(test '(1 2 3 4) (append! app-a (list 3 4)))
(test '(1 2 3) (append! '() (list 1 2) (list 3)))
(define app-b (list 1))
(test '(1) (append! app-b))
(test '(1 2) (append! (list 1) (list 2)))
(call-with-values (lambda () (unzip1 '((1 a) (2 b)))) (lambda (a) (test '(1 2) a)))
(call-with-values (lambda () (unzip2 '((1 a) (2 b))))
  (lambda (a b) (test '(1 2) a) (test '(a b) b)))
(call-with-values (lambda () (unzip3 '((1 a x) (2 b y))))
  (lambda (a b c) (test '(1 2) a) (test '(a b) b) (test '(x y) c)))
(test 'bad-tuple (guard (e (#t 'bad-tuple)) (unzip2 '((1 a) (2)))))
(test '((1 a) (2 b)) (zip '(1 2) '(a b)))
(test 2 (count even? '(1 2 3 4)))
(test '((1 . a) (2 . b)) (alist-copy '((1 . a) (2 . b))))
(define original (list (cons 1 'a)))
(define copied (alist-copy original))
(test #t (equal? original copied))
(test #f (eq? (car original) (car copied)))
(test-end)

;; --------------------------------------------------------------- iteration
(test-begin "Iteration")

(test 6 (fold + 0 '(1 2 3)))
(test 2 (fold - 0 '(1 2 3)))
(test '(3 2 1) (fold cons '() '(1 2 3)))
(test 33 (fold + 0 '(1 2) '(10 20)))
(test 9 (fold (lambda (x acc) (max x acc)) 0 '(3 9 2)))
(test 2 (fold-right - 0 '(1 2 3)))
(test '(1 2 3) (fold-right cons '() '(1 2 3)))
(test 33 (fold-right + 0 '(1 2) '(10 20)))
(test '(3 2 1) (pair-fold (lambda (p acc) (cons (car p) acc)) '() '(1 2 3)))
(test '(1 2 3) (pair-fold-right (lambda (p acc) (cons (car p) acc)) '() '(1 2 3)))
(test 6 (reduce + 0 '(1 2 3)))
(test 99 (reduce + 99 '()))
(test 2 (reduce-right - 0 '(1 2 3)))
(test 99 (reduce-right + 99 '()))
(test '(1 4 9) (unfold (lambda (x) (> x 3)) (lambda (x) (* x x)) (lambda (x) (+ x 1)) 1))
(test '(1 2 3 (tail 4))
      (unfold (lambda (x) (> x 3)) (lambda (x) x) (lambda (x) (+ x 1)) 1
              (lambda (x) (list 'tail x))))
(test '(9 4 1) (unfold-right (lambda (x) (> x 3)) (lambda (x) (* x x)) (lambda (x) (+ x 1)) 1))
(test '(3 2 1 tail)
      (unfold-right (lambda (x) (> x 3)) (lambda (x) x) (lambda (x) (+ x 1)) 1 '(tail)))
(test '(1 -1 2 -2) (append-map (lambda (x) (list x (- x))) '(1 2)))
(test '() (append-map (lambda (x) (list x)) '()))
(test '(2 4) (filter-map (lambda (x) (if (even? x) x #f)) '(1 2 3 4)))
(test '(1 2) (map! (lambda (x) x) '(1 2)))
(test '(1 2) (map-in-order (lambda (x) x) '(1 2)))
(test '(3 2 1)
      (let ((acc '()))
        (pair-for-each (lambda (p) (set! acc (cons (car p) acc))) '(1 2 3))
        acc))
(test '(1 2 3) (append-map! list '(1 2 3)))
(test-end)

;; --------------------------------------------------------------- filtering
(test-begin "Filtering")

(test '(2 4) (filter even? '(1 2 3 4)))
(test '(1 3) (remove even? '(1 2 3 4)))
(test '(1 3) (filter! odd? '(1 2 3 4)))
(test '(1 3) (remove! even? '(1 2 3 4)))
(call-with-values (lambda () (partition even? '(1 2 3 4)))
  (lambda (yes no) (test '(2 4) yes) (test '(1 3) no)))
(call-with-values (lambda () (partition! even? '(1 2 3 4)))
  (lambda (yes no) (test '(2 4) yes) (test '(1 3) no)))
(test-end)

;; --------------------------------------------------------------- searching
(test-begin "Searching")

(test 4 (find even? '(1 3 4 5)))
(test '(4 5) (find-tail even? '(1 3 4 5)))
(test #f (find-tail even? '(1 3)))
(test 1 (list-index even? '(1 2 3)))
(test #f (list-index even? '(1 3)))
(test #t (any even? '(1 2 3)))
(test #f (any even? '(1 3)))
(test 20 (any (lambda (x) (and (even? x) (* x 10))) '(1 2 3)))
(test #t (every even? '(2 4)))
(test #f (every even? '(2 3)))
(test 40 (every (lambda (x) (and (even? x) (* x 10))) '(2 4)))
(test #t (every even? '()))
(test #t (any < '(1 5) '(3 2)))
(test #t (every < '(1 2) '(3 4)))
(test #f (every < '(1 5) '(3 2)))
(test #t (any even? (vector 1 2 3)))
(test '(1 2) (take-while (lambda (x) (< x 3)) '(1 2 3 4)))
(test '(3 4) (drop-while (lambda (x) (< x 3)) '(1 2 3 4)))
(test '(1 2) (take-while! (lambda (x) (< x 3)) '(1 2 3 4)))
(call-with-values (lambda () (span even? '(2 4 5 6)))
  (lambda (a b) (test '(2 4) a) (test '(5 6) b)))
(call-with-values (lambda () (break even? '(1 3 4 5)))
  (lambda (a b) (test '(1 3) a) (test '(4 5) b)))
(call-with-values (lambda () (span! even? '(2 4 5 6)))
  (lambda (a b) (test '(2 4) a) (test '(5 6) b)))
(call-with-values (lambda () (break! even? '(1 3 4 5)))
  (lambda (a b) (test '(1 3) a) (test '(4 5) b)))
(test-end)

;; ---------------------------------------------------------------- deleting
(test-begin "Deleting")

(test '(1 3) (delete 2 '(1 2 3)))
(test '(1 3) (delete! 2 '(1 2 3)))
(test '(1 2 3) (delete-duplicates '(1 2 1 3 2)))
(test '(1 2 3) (delete-duplicates! '(1 2 1 3 2)))
(test '("a" "b") (delete-duplicates '("a" "b" "a")))
(test-end)

;; ------------------------------------------------------------------- sets
(test-begin "Set operations")

(test #f (lset<= = '(1 2) '(1 2 3)))
(test #t (lset<= = '(1 2 3) '(1 2)))
(test #t (lset<= = '(1) '(1) '(1)))
(test #t (lset<= = '(1)))
(test #t (lset= = '(1 2) '(2 1)))
(test #f (lset= = '(1) '(1 2)))
(test '(1 2 3 4) (lset-adjoin = '(1 2) 3 2 4))
(test '(1) (lset-adjoin = '() 1))
(test '(1 2) (lset-adjoin = '(1 2) 1))
(test '(1 2 3 4) (lset-union = '(1 2) '(2 3) '(3 4)))
(test '() (lset-union =))
(test '(1 2 3) (lset-union = '(1 1 2) '(2 3)))
(test '("a" "b" "c") (lset-union string=? '("a" "b") '("b" "c")))
(test '(2 3) (lset-intersection = '(1 2 3) '(2 3 4)))
(test '(1) (lset-intersection = '(1 2) '(1 2) '(1)))
(test '(1 3) (lset-difference = '(1 2 3) '(2)))
(test '(1) (lset-difference = '(1 2 3) '(2) '(3)))
(test '(1 3) (lset-xor = '(1 2) '(2 3)))
(test '(1 4) (lset-xor = '(1 2 3) '(2 3 4)))
(call-with-values (lambda () (lset-diff+intersection = '(1 2 3) '(2 3 4)))
  (lambda (d i) (test '(1) d) (test '(2 3) i)))
(test-end)

;; ------------------------------------------ sharing with (goscheme fast)
(test-begin "Shared with (goscheme fast)")

;; The two libraries export the same bindings for these, so the result does not
;; depend on which import came last.
(test '(1 2 3) (sort (list 3 1 2)))
(test '(1 3) (filter odd? '(1 2 3)))
(test '(0 1 2) (iota 3))
(test 3 (length (iota 3)))
(test '((1 a) (2 b)) (zip '(1 2) '(a b)))
(test 1 (list-index even? '(1 2 3)))
(test '(1 3) (delete 2 '(1 2 3)))
(test '(1 2) (take 2 '(1 2 3)))
(test '(3) (drop 2 '(1 2 3)))
(test-end)

(test-end)
